name: Publish Plugin

on: [ workflow_dispatch ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Publish
        run: |
          chmod +x gradlew
          ./gradlew plugin:publish
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_TOKEN: ${{ secrets.MAVEN_REPO_TOKEN }}

      - name: Stop Gradle
        run: ./gradlew --stop
