name: Publish Plugin

on: [ workflow_dispatch ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Publish on Plugin Portal
        run: ./gradlew plugin:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop Gradle
        run: ./gradlew --stop
